SELECT HACKER_ID, NAME, COUNT(CHALLENGE_ID) CHALLENGE_COUNT
FROM HACKERS INNER JOIN CHALLENGES USING (HACKER_ID)
GROUP BY HACKER_ID, NAME
HAVING CHALLENGE_COUNT = 
    (SELECT COUNT(CHALLENGE_ID) TOTAL FROM CHALLENGES 
     GROUP BY HACKER_ID ORDER BY TOTAL DESC LIMIT 1)
OR CHALLENGE_COUNT IN
    (SELECT TOTAL FROM
        (SELECT COUNT(CHALLENGE_ID) TOTAL FROM CHALLENGES
         GROUP BY HACKER_ID) TEMP
     GROUP BY TOTAL 
     HAVING COUNT(TOTAL) = 1)
ORDER BY CHALLENGE_COUNT DESC, HACKER_ID