SELECT HACKER_ID, NAME, SUM(MAX_SCORE) TOTAL
FROM HACKERS INNER JOIN
    (SELECT HACKER_ID, MAX(SCORE) MAX_SCORE
     FROM SUBMISSIONS GROUP BY HACKER_ID, CHALLENGE_ID) CHALLENGES
USING (HACKER_ID)
GROUP BY HACKER_ID, NAME
HAVING TOTAL <> 0
ORDER BY TOTAL DESC, HACKER_ID