SELECT ID, AGE, COINS_NEEDED, POWER
FROM WANDS W INNER JOIN WANDS_PROPERTY P USING (CODE)
WHERE IS_EVIL = 0 AND COINS_NEEDED = 
    (SELECT MIN(COINS_NEEDED)
     FROM WANDS INNER JOIN WANDS_PROPERTY USING (CODE) 
     WHERE POWER = W.POWER AND AGE = P.AGE)
ORDER BY POWER DESC, AGE DESC