SELECT
(CASE WHEN GRADE >= 8 THEN NAME ELSE NULL END) AS NAME, GRADE, MARKS
FROM STUDENTS, GRADES
WHERE MARKS BETWEEN MIN_MARK AND MAX_MARK
ORDER BY GRADE DESC, (CASE WHEN GRADE >= 8 THEN NAME ELSE MARKS END)