SELECT H.HACKER_ID, H.NAME
FROM HACKERS H
INNER JOIN SUBMISSIONS S USING (HACKER_ID)
INNER JOIN CHALLENGES C USING (CHALLENGE_ID)
INNER JOIN DIFFICULTY D USING (DIFFICULTY_LEVEL)
WHERE S.SCORE = D.SCORE
GROUP BY HACKER_ID, NAME
HAVING COUNT(H.HACKER_ID) > 1
ORDER BY COUNT(H.HACKER_ID) DESC, H.HACKER_ID