SET @r1 = 0, @r2 = 0, @r3 = 0, @r4 = 0;
SELECT MAX(DOCTOR), MAX(PROFESSOR), MAX(SINGER), MAX(ACTOR)
FROM (
    SELECT CASE WHEN OCCUPATION = 'Doctor' THEN @r1 := @r1 + 1
                WHEN OCCUPATION = 'Professor' THEN @r2 := @r2 + 1
                WHEN OCCUPATION = 'Singer' THEN @r3 := @r3 + 1
                WHEN OCCUPATION = 'Actor' THEN @r4 := @r4 + 1
            END AS ROWNUM,
    CASE WHEN OCCUPATION = 'Doctor' THEN NAME END AS DOCTOR,
    CASE WHEN OCCUPATION = 'Professor' THEN NAME END AS PROFESSOR,
    CASE WHEN OCCUPATION = 'Singer' THEN NAME END AS SINGER,
    CASE WHEN OCCUPATION = 'Actor' THEN NAME END AS ACTOR
    FROM OCCUPATIONS
    ORDER BY NAME
) PADS
GROUP BY ROWNUM