SELECT CONTEST_ID, HACKER_ID, NAME,
        IFNULL(SUM(TOTAL_SUBMISSIONS), 0) T_SUBMISSIONS,
        IFNULL(SUM(TOTAL_ACCEPTED_SUBMISSIONS), 0) T_ACCEPTED_SUBMISSIONS,
        IFNULL(SUM(TOTAL_VIEWS), 0) T_VIEWS,
        IFNULL(SUM(TOTAL_UNIQUE_VIEWS), 0) T_UNIQUE_VIEWS
FROM CONTESTS
INNER JOIN COLLEGES USING (CONTEST_ID)
INNER JOIN CHALLENGES USING (COLLEGE_ID)
LEFT JOIN (SELECT CHALLENGE_ID, 
           SUM(TOTAL_VIEWS) TOTAL_VIEWS, 
           SUM(TOTAL_UNIQUE_VIEWS) TOTAL_UNIQUE_VIEWS
           FROM VIEW_STATS GROUP BY CHALLENGE_ID) VS
           USING (CHALLENGE_ID)
LEFT JOIN (SELECT CHALLENGE_ID, 
           SUM(TOTAL_SUBMISSIONS) TOTAL_SUBMISSIONS, 
           SUM(TOTAL_ACCEPTED_SUBMISSIONS) TOTAL_ACCEPTED_SUBMISSIONS
           FROM SUBMISSION_STATS GROUP BY CHALLENGE_ID) SS
           USING (CHALLENGE_ID)
GROUP BY CONTEST_ID, HACKER_ID, NAME
HAVING T_VIEWS + T_UNIQUE_VIEWS + 
        T_SUBMISSIONS + T_ACCEPTED_SUBMISSIONS > 0
ORDER BY CONTEST_ID