-- Solution 1
SELECT MAX(SALARY * MONTHS), COUNT(*) FROM EMPLOYEE
WHERE SALARY * MONTHS = (SELECT MAX(SALARY * MONTHS) FROM EMPLOYEE);

-- Solution 2
SELECT (SALARY * MONTHS) AS EARNINGS, COUNT(*) FROM EMPLOYEE
GROUP BY EARNINGS ORDER BY EARNINGS DESC LIMIT 1;